# Model configuration for SimpleNet
name: netl${model.object.num_layers}d${model.object.latent_dim} # name of the model configuration
object:
  _target_: modules.models.simple_net.Net
  num_layers: 2
  latent_dim: 128