# Training configuration for the model model
name: basic # name of the training configuration
device: cuda
loss: 
  _target_: torch.nn.NLLLoss
optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: 'min'
  factor: 0.1
  patience: 3
epochs: 10
gradient_accumulation_steps: 5
loggers:
  tensorboard:
    _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    save_dir: ${save_dir}
    name: tb
  csv:
    _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
    save_dir: ${save_dir}
    name: csv
