# @package _global_
#########################################################
# Task-specific parameters
#########################################################
defaults:
  - _self_
  - path: relative

# Base directory for loading results
base_dir: ${path.base_path_models}
max_pool: 8  # Maximum number of parallel processes for loading results

# Output path name
name: report_${now:%Y-%m-%d_%H-%M-%S}

#########################################################
# Hydraqol parameters (see modules/utils/hydraqol.py)
#########################################################
# Save directory for outputs
save_dir: ${path.base_path}/reports/${name}
# Mode configuration (base, force, clean, check) 
mode: base
# Retry configuration
retry:
  max_retries: 3
  delay: 5  # seconds

#########################################################
# Hydra parameters
#########################################################
hydra:
  run:
    dir: ${path.base_path}/outputs/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.name}
  sweep:
    dir: ${path.base_path}/outputs/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.name}
    subdir: ${hydra.job.num}
