# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra: 
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  launcher: # https://hydra.cc/docs/plugins/submitit_launcher/
    setup: [
      "echo '# Loading python module!'", "module load Python/3.10.4 2>&1",
      "echo '# List of modules:'", "module list 2>&1",
      "echo '# Current working directory:'", "pwd", 
      "echo '# List of folders in pwd:'", "ls",
      "echo '# Activate venv!'", ". .venv/bin/activate", 
      "echo '# Which python:'", "which python"]
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    cpus_per_task: 20
    #mem_per_cpu: 20000
    array_parallelism: 50 #5
    timeout_min: 300
    tasks_per_node: 1 #4
    #account: p0021919