# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
training:
  device: cuda
hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    cpus_per_task: 2
    mem_gb: 8
    gpus_per_node: 1
    timeout_min: 60
    tasks_per_node: 1
    array_parallelism: 2
